name: image-text-classification
services:
- name: web
  source_dir: /
  github:
    repo: dusharakalubowila/image-text-classification
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: PORT
    value: "8080"
  - key: PYTHONPATH
    value: "/app"
